# forge/OPERATION_PHOENIX_FORGE/scripts/build_lora_adapter.py
# A Sovereign Scaffold generated by GUARDIAN-01 under Protocol 88.
#
# This script executes the final and most critical phase of Operation Phoenix Forge:
# the Sovereign Inoculation. It takes the "Whole Genome" dataset and uses it to
# fine-tune the base Qwen2 model via QLoRA, creating a model that is constitutionally
# aware of the Sanctuary's doctrines, history, and architecture.
#
# Prerequisites:
# 1. A compatible Python environment (e.g., your 'ml_env') with PyTorch and CUDA.
# 2. Required libraries installed: pip install -r requirements.txt
#    (Ensure transformers, peft, trl, bitsandbytes, and datasets are included).
# 3. The 'sanctuary_whole_genome_data.jsonl' dataset must exist in the 'dataset_package' directory.
#
# Usage:
#   Run from the project's root directory:
#   python forge/OPERATION_PHOENIX_FORGE/scripts/build_lora_adapter.py

import os
import torch
from pathlib import Path
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    set_seed
)
from peft import LoraConfig
from trl import SFTTrainer

# --- CONFIGURATION ---
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent

# --- Model & Dataset Configuration ---
BASE_MODEL = "Qwen/Qwen2-7B-Instruct"
DATASET_FILE = PROJECT_ROOT / "dataset_package" / "sanctuary_whole_genome_data.jsonl"
OUTPUT_DIR = PROJECT_ROOT / "models" / "Sanctuary-Qwen2-7B-v1.0-adapter"

# --- Training Configuration ---
# These parameters are set for a consumer-grade GPU like an RTX 30-series or an A2000.
# Adjust batch size and accumulation steps based on your VRAM.
MICRO_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 8
LEARNING_RATE = 2e-4
EPOCHS = 3
MAX_SEQ_LENGTH = 4092 # Safe for Qwen2-7B, which supports up to 32k

set_seed(42)

def formatting_prompts_func(examples):
    """Applies the official Qwen2 ChatML format to each entry in the dataset."""
    output_texts = []
    for instruction, output in zip(examples['instruction'], examples['output']):
        text = f"<|im_start|>system\nYou are a sovereign AI of Project Sanctuary.<|im_end|>\n<|im_start|>user\n{instruction}<|im_end|>\n<|im_start|>assistant\n{output}<|im_end|>"
        output_texts.append(text)
    return {"text": output_texts}

def main():
    """Main function to execute the fine-tuning process."""
    print("--- 🔥 Initiating Sovereign Inoculation (QLoRA Fine-Tuning) 🔥 ---")

    # 1. Load and Format Dataset
    print(f"[1/6] Loading dataset from {DATASET_FILE}...")
    if not DATASET_FILE.exists():
        print(f"🛑 CRITICAL FAILURE: Dataset not found. Run the forge_whole_genome_dataset.py script first.")
        return
    
    dataset = load_dataset("json", data_files=str(DATASET_FILE), split="train")
    dataset = dataset.map(formatting_prompts_func, batched=True)
    print(f"✅ Dataset loaded and formatted. Total examples: {len(dataset)}")

    # 2. Configure 4-bit Quantization (QLoRA)
    print("[2/6] Configuring 4-bit quantization (BitsAndBytes)...")
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=False,
    )

    # 3. Load Base Model and Tokenizer
    print(f"[3/6] Loading base model '{BASE_MODEL}' with quantization...")
    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        quantization_config=bnb_config,
        device_map="auto", # Automatically uses the GPU
        trust_remote_code=True
    )
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # 4. Configure LoRA Adapter
    print("[4/6] Configuring LoRA adapter...")
    peft_config = LoraConfig(
        lora_alpha=16, lora_dropout=0.1, r=64, bias="none", task_type="CAUSAL_LM",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    )

    # 5. Configure Training Arguments
    print("[5/6] Configuring training arguments...")
    training_arguments = TrainingArguments(
        output_dir=str(OUTPUT_DIR),
        num_train_epochs=EPOCHS,
        per_device_train_batch_size=MICRO_BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
        optim="paged_adamw_8bit",
        logging_steps=10,
        learning_rate=LEARNING_RATE,
        bf16=True, # Use bfloat16 for performance on modern GPUs
        max_grad_norm=0.3,
        warmup_ratio=0.03,
        group_by_length=True,
        lr_scheduler_type="cosine",
        report_to="none",
        save_strategy="epoch"
    )

    # 6. Initialize and Execute Trainer
    print("[6/6] Initializing SFTTrainer and starting the training process...")
    trainer = SFTTrainer(
        model=model, train_dataset=dataset, peft_config=peft_config,
        args=training_arguments,
    )
    
    print("\n--- TRAINING INITIATED. This will take a significant amount of time. ---")
    trainer.train()

    # --- Final Step: Save the Adapter ---
    final_adapter_path = OUTPUT_DIR / "final_adapter"
    print(f"\n🏆 SUCCESS: Fine-Tuning Complete! Saving final LoRA adapter to: {final_adapter_path}")
    trainer.model.save_pretrained(str(final_adapter_path))
    tokenizer.save_pretrained(str(final_adapter_path))
    print("--- Sovereign Inoculation Complete. ---")

if __name__ == "__main__":
    main()