version: "3.8"

networks:
  sanctuary-net:
    external: true

services:
  # -------------------------------------------------------------
  # Cluster 1: Utility & Network
  # -------------------------------------------------------------
  utils:
    container_name: sanctuary-utils
    build: 
      context: ./mcp_servers
      dockerfile: utils/Dockerfile
    networks: [sanctuary-net]
    expose: ["8000"]
    ports:
      - "${SANCTUARY_UTILS_PORT:-8100}:8000"
    command: ["python", "-m", "mcp_servers.utils.server"]
    env_file: .env
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHON_PATH=/app

  network:
    container_name: sanctuary-network
    build:
      context: ./mcp_servers
      dockerfile: utils/Dockerfile
    networks: [sanctuary-net]
    expose: ["8002"]
    ports:
      - "${SANCTUARY_NETWORK_PORT:-8102}:8002"
    command: ["python", "-m", "mcp_servers.network.server"]
    volumes:
       - ./mcp_servers:/app/mcp_servers
    env_file: .env
    environment:
      - PORT=8002
      - PYTHONUNBUFFERED=1
      - PYTHON_PATH=/app

  # -------------------------------------------------------------
  # Cluster 2: SysAdmin (Filesystem & Git)
  # -------------------------------------------------------------
  filesystem:
    container_name: sanctuary-filesystem
    build:
      context: ./mcp_servers
      dockerfile: code/Dockerfile
    networks: [sanctuary-net]
    expose: ["8001"]
    ports:
      - "${SANCTUARY_FILESYSTEM_PORT:-8101}:8001"
    volumes:
      - .:/Projects/Project_Sanctuary
    command: ["python", "-m", "mcp_servers.code.server"]
    env_file: .env
    environment:
      - PORT=8001
      - PROJECT_ROOT=/Projects/Project_Sanctuary
      - PYTHONUNBUFFERED=1

  git:
    container_name: sanctuary-git
    build:
      context: ./mcp_servers
      dockerfile: git/Dockerfile
    networks: [sanctuary-net]
    expose: ["8003"]
    ports:
      - "${SANCTUARY_GIT_PORT:-8103}:8003"
    volumes:
      - .:/Projects/Project_Sanctuary
      - ~/.gitconfig:/root/.gitconfig:ro
    command: ["python", "-m", "mcp_servers.git.server"]
    env_file: .env
    environment:
      - PORT=8003
      - REPO_PATH=/Projects/Project_Sanctuary
      - GIT_BASE_DIR=/Projects/Project_Sanctuary
      - PYTHONUNBUFFERED=1

  # -------------------------------------------------------------
  # Cluster 3: Intelligence (Cortex)
  # -------------------------------------------------------------
  cortex:
    container_name: sanctuary-cortex
    build:
      context: ./mcp_servers
      dockerfile: rag_cortex/Dockerfile
    networks: [sanctuary-net]
    expose: ["8004"]
    ports:
      - "${SANCTUARY_CORTEX_PORT:-8104}:8004"
    volumes:
      - .:/Projects/Project_Sanctuary
      - ./00_CHRONICLE:/app/00_CHRONICLE
      - ./01_PROTOCOLS:/app/01_PROTOCOLS
    command: ["python", "-m", "mcp_servers.rag_cortex.server"]
    env_file: .env
    environment:
      - PORT=8004
      - VECTOR_DB_URL=http://sanctuary-vector-db:8000
      - OLLAMA_URL=http://sanctuary-ollama-mcp:11434
      - PROJECT_ROOT=/Projects/Project_Sanctuary
      - PYTHONUNBUFFERED=1

  # -------------------------------------------------------------
  # Backends (Internal)
  # -------------------------------------------------------------
  vector-db:
    container_name: sanctuary-vector-db
    image: chromadb/chroma:latest
    networks: [sanctuary-net]
    expose: ["8000"]
    # Internal port 8000, mapped to host 8005 if debug needed
    ports:
      - "8005:8000"
    volumes:
      - .vector_data:/chroma/chroma

  ollama:
    container_name: sanctuary-ollama-mcp
    image: ollama/ollama:latest
    networks: [sanctuary-net]
    expose: ["11434"]
    volumes:
      - .ollama_models:/root/.ollama
