#!/bin/bash
# Shim for /workflow-learning-loop
# Auto-generated by Agent

# ---------------------------------------------------------
# RED TEAM REMEDIATION: CV-01 (Human Gate)
# ---------------------------------------------------------
echo "=============================================="
echo "🛡️  HUMAN GATE REQURIED: LEARNING LOOP 🛡️"
echo "=============================================="
echo "You are about to START the Protocol 128 Learning Loop."
echo "This will eventually modify .agent/learning artifacts."
echo ""
echo "Type 'PROCEED' to start."
read -p "> " approval

if [[ "$approval" != "PROCEED" ]]; then
    echo "❌ Approval not given. Aborting."
    exit 1
fi

python3 tools/cli.py workflow run --name workflow-learning-loop "$@"
