#!/bin/bash
# Shim for /workflow-ingest
# Auto-generated by Agent

# ---------------------------------------------------------
# RED TEAM REMEDIATION: CV-01 (Human Gate)
# ---------------------------------------------------------
echo "=============================================="
echo "🛡️  HUMAN GATE REQURIED: INGEST MEMORY 🛡️"
echo "=============================================="
echo "You are about to INGEST artifacts into the RAG Brain."
echo "This modifies the Neural Knowledge Base."
echo ""
echo "Type 'PROCEED' to execute."
read -p "> " approval

if [[ "$approval" != "PROCEED" ]]; then
    echo "❌ Approval not given. Aborting."
    exit 1
fi

python3 tools/cli.py workflow run --name workflow-ingest "$@"
