#!/bin/bash
# Auto-generated tool migration script

echo 'Updating tools/standalone/xml-to-markdown/unpacking.mmd -> plugins/rlm-factory/skills/rlm-curator/references/unpacking.mmd...'
sed -i '' 's/tools\/standalone\/xml-to-markdown\/unpacking\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/unpacking\.mmd/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/standalone\/xml-to-markdown\/unpacking\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/unpacking\.mmd/g' "broken_tool_references.md"
echo 'Updating tools/bridge/sync_skills.py -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/sync_skills\.py/plugins\/plugin-mapper\//g' "01_PROTOCOLS/128_Hardened_Learning_Loop.md"
sed -i '' 's/tools\/bridge\/sync_skills\.py/plugins\/plugin-mapper\//g' "temp/REAL_RED_TEAM_BUNDLE.md"
sed -i '' 's/tools\/bridge\/sync_skills\.py/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/file-manifest-schema.json -> plugins/context-bundler/resources/file-manifest-schema.json...'
sed -i '' 's/tools\/standalone\/context-bundler\/file-manifest-schema\.json/plugins\/context-bundler\/resources\/file-manifest-schema\.json/g' "specs/0006-rebuild-constitution/RED_TEAM_BUNDLE.md"
sed -i '' 's/tools\/standalone\/context-bundler\/file-manifest-schema\.json/plugins\/context-bundler\/resources\/file-manifest-schema\.json/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/standalone\/context-bundler\/file-manifest-schema\.json/plugins\/context-bundler\/resources\/file-manifest-schema\.json/g' "temp/bundler-architecture-review-manifest.json"
echo 'Updating tools/standalone/context-bundler/base-manifests-index.json -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests-index\.json/plugins\/context-bundler\//g' "docs/tools/standalone/context-bundler/architecture.md"
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests-index\.json/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests-index\.json/plugins\/context-bundler\//g' "temp/bundler-architecture-review-manifest.json"
echo 'Updating tools/codify/utils/capture-code-snapshot.js -> plugins/context-bundler/...'
sed -i '' 's/tools\/codify\/utils\/capture-code-snapshot\.js/plugins\/context-bundler\//g' "tools/tool_inventory.json"
sed -i '' 's/tools\/codify\/utils\/capture-code-snapshot\.js/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/codify\/utils\/capture-code-snapshot\.js/plugins\/context-bundler\//g' "specs/0004-refactor-rag-ingest/scratchpad.md"
echo 'Updating tools/orchestrator/proof_check.py -> plugins/agent-loops/skills/orchestrator/scripts/proof_check.py...'
sed -i '' 's/tools\/orchestrator\/proof_check\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/proof_check\.py/g' "tools/tool_inventory.json"
sed -i '' 's/tools\/orchestrator\/proof_check\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/proof_check\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/orchestrator\/proof_check\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/proof_check\.py/g' "scripts/update_legacy_paths.py"
echo 'Updating tools/investigate/utils/rlmConfigResolver.js -> plugins/rlm-factory/...'
sed -i '' 's/tools\/investigate\/utils\/rlmConfigResolver\.js/plugins\/rlm-factory\//g' "tools/tool_inventory.json"
sed -i '' 's/tools\/investigate\/utils\/rlmConfigResolver\.js/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/codify/vector/ingest.py -> plugins/vector-db/skills/vector-db-agent/scripts/ingest.py...'
sed -i '' 's/tools\/codify\/vector\/ingest\.py/plugins\/vector-db\/skills\/vector-db-agent\/scripts\/ingest\.py/g' "specs/0001-mcp-to-cli-migration/scratchpad.md"
sed -i '' 's/tools\/codify\/vector\/ingest\.py/plugins\/vector-db\/skills\/vector-db-agent\/scripts\/ingest\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/codify\/vector\/ingest\.py/plugins\/vector-db\/skills\/vector-db-agent\/scripts\/ingest\.py/g' "tools/README.md"
sed -i '' 's/tools\/codify\/vector\/ingest\.py/plugins\/vector-db\/skills\/vector-db-agent\/scripts\/ingest\.py/g' "docs/tools/standalone/vector-db/workflow.mmd"
echo 'Updating tools/retrieve/vector/query.py -> plugins/vector-db/skills/vector-db-agent/scripts/query.py...'
sed -i '' 's/tools\/retrieve\/vector\/query\.py/plugins\/vector-db\/skills\/vector-db-agent\/scripts\/query\.py/g' "specs/0001-mcp-to-cli-migration/scratchpad.md"
sed -i '' 's/tools\/retrieve\/vector\/query\.py/plugins\/vector-db\/skills\/vector-db-agent\/scripts\/query\.py/g' "tools/README.md"
sed -i '' 's/tools\/retrieve\/vector\/query\.py/plugins\/vector-db\/skills\/vector-db-agent\/scripts\/query\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/retrieve\/vector\/query\.py/plugins\/vector-db\/skills\/vector-db-agent\/scripts\/query\.py/g' "docs/diagrams/rlm/rlm_late_binding_flow.mmd"
sed -i '' 's/tools\/retrieve\/vector\/query\.py/plugins\/vector-db\/skills\/vector-db-agent\/scripts\/query\.py/g' "docs/tools/standalone/vector-db/workflow.mmd"
echo 'Updating tools/bridge/ -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\//plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/bridge\//plugins\/plugin-mapper\//g' "scripts/reconcile_tool_references.py"
echo 'Updating tools/bridge -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge/plugins\/plugin-mapper\//g' "scripts/reconcile_tool_references.py"
echo 'Updating tools/codify/rlm -> plugins/rlm-factory/...'
sed -i '' 's/tools\/codify\/rlm/plugins\/rlm-factory\//g' "ADRs/098-vector-and-rlm-tool-strategy.md"
sed -i '' 's/tools\/codify\/rlm/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/codify/rlm/refresh_cache.py -> plugins/rlm-factory/...'
sed -i '' 's/tools\/codify\/rlm\/refresh_cache\.py/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/codify\/rlm\/refresh_cache\.py/plugins\/rlm-factory\//g' "scripts/update_legacy_paths.py"
echo 'Updating tools/codify/vector -> plugins/vector-db/...'
sed -i '' 's/tools\/codify\/vector/plugins\/vector-db\//g' "ADRs/098-vector-and-rlm-tool-strategy.md"
sed -i '' 's/tools\/codify\/vector/plugins\/vector-db\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/context-bundler/ -> plugins/context-bundler/...'
sed -i '' 's/tools\/context-bundler\//plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/retrieve/rlm/fetch_tool_context.py -> plugins/rlm-factory/...'
sed -i '' 's/tools\/retrieve\/rlm\/fetch_tool_context\.py/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/retrieve\/rlm\/fetch_tool_context\.py/plugins\/rlm-factory\//g' "scripts/update_legacy_paths.py"
echo 'Updating tools/standalone/context-bundler/ -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\//plugins\/context-bundler\//g' "docs/tools/standalone/context-bundler/architecture.md"
sed -i '' 's/tools\/standalone\/context-bundler\//plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/architecture.md -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/architecture\.md/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/INSTALL.md -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/INSTALL\.md/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/UNPACK_INSTRUCTIONS.md -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/UNPACK_INSTRUCTIONS\.md/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/agent-unpacking-process.mmd -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/agent-unpacking-process\.mmd/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/architecture.mmd -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/architecture\.mmd/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/base-manifests -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/base-manifests/ -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\//plugins\/context-bundler\//g' "specs/0006-rebuild-constitution/RED_TEAM_BUNDLE.md"
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\//plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\//plugins\/context-bundler\//g' "docs/diagrams/workflows/curate-bundle.mmd"
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\//plugins\/context-bundler\//g' "ADRs/097_base_manifest_inheritance_architecture.md"
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\//plugins\/context-bundler\//g' "specs/0002-spec-0002/tasks.md"
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\//plugins\/context-bundler\//g' "ADRs/089_modular_manifest_pattern.md"
echo 'Updating tools/standalone/context-bundler/base-manifests/base-bootstrap-file-manifest.json -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\/base-bootstrap-file-manifest\.json/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/base-manifests/base-context-bundler-file-manifest.json -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\/base-context-bundler-file-manifest\.json/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/base-manifests/base-generic-file-manifest.json -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\/base-generic-file-manifest\.json/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/base-manifests/base-guardian-file-manifest.json -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\/base-guardian-file-manifest\.json/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/base-manifests/base-learning-audit-core.json -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\/base-learning-audit-core\.json/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/base-manifests/base-learning-file-manifest.json -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\/base-learning-file-manifest\.json/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/base-manifests/base-red-team-file-manifest.json -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\/base-red-team-file-manifest\.json/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/bundler-internal-logic.mmd -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/bundler-internal-logic\.mmd/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/context-bundler-manifest.json -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/context-bundler-manifest\.json/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/docs/tools/standalone/context-bundler/agent-unpacking-process.mmd -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/docs\/tools\/standalone\/context-bundler\/agent-unpacking-process\.mmd/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/docs/tools/standalone/context-bundler/architecture.md -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/docs\/tools\/standalone\/context-bundler\/architecture\.md/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/docs/tools/standalone/context-bundler/bundler-internal-logic.mmd -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/docs\/tools\/standalone\/context-bundler\/bundler-internal-logic\.mmd/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/docs/tools/standalone/context-bundler/setup-lifecycle-workflow.mmd -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/docs\/tools\/standalone\/context-bundler\/setup-lifecycle-workflow\.mmd/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/setup-lifecycle-workflow.mmd -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/setup-lifecycle-workflow\.mmd/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/tool-bundle.md -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/tool-bundle\.md/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/INSTALL.md -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/INSTALL\.md/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/SYSTEM_REQUIREMENTS.md -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/SYSTEM_REQUIREMENTS\.md/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/UNPACK_INSTRUCTIONS.md -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/UNPACK_INSTRUCTIONS\.md/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/rlm-factory-manifest.json -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/rlm-factory-manifest\.json/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/tool-bundle.md -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/tool-bundle\.md/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/tool-manifest.json -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/tool-manifest\.json/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/vector-db/workflow.mmd -> plugins/vector-db/...'
sed -i '' 's/tools\/standalone\/vector-db\/workflow\.mmd/plugins\/vector-db\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/LLM_UNPACKAGING_INSTRUCTIONS.md -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/LLM_UNPACKAGING_INSTRUCTIONS\.md/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/README.md -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/README\.md/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/agent-worktree-reference.md -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/agent-worktree-reference\.md/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/bridge_architecture_overview.md -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/bridge_architecture_overview\.md/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/bridge_mapping_matrix.md -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/bridge_mapping_matrix\.md/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/bridge_process.mmd -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/bridge_process\.mmd/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/spec_kitty_bridge_bundle.md -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/spec_kitty_bridge_bundle\.md/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/speckit_system_bridge.py -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/speckit_system_bridge\.py/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/standard-spec-kitty-workflow.md -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/standard-spec-kitty-workflow\.md/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/standard-spec-kitty-workflow.mmd -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/standard-spec-kitty-workflow\.mmd/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/sync_ -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/sync_/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/sync_rules.py -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/sync_rules\.py/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/sync_workflows.py -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/sync_workflows\.py/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/tool_inventory.json -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/tool_inventory\.json/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/bridge/verify_bridge_integrity.py -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\/verify_bridge_integrity\.py/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/codify/rlm/debug_rlm.py -> plugins/rlm-factory/skills/rlm-curator/scripts/debug_rlm.py...'
sed -i '' 's/tools\/codify\/rlm\/debug_rlm\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/debug_rlm\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/codify\/rlm\/debug_rlm\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/debug_rlm\.py/g' "scripts/update_legacy_paths.py"
echo 'Updating tools/codify/rlm/distiller.py -> plugins/rlm-factory/skills/rlm-curator/scripts/distiller.py...'
sed -i '' 's/tools\/codify\/rlm\/distiller\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/distiller\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/codify\/rlm\/distiller\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/distiller\.py/g' "scripts/update_legacy_paths.py"
echo 'Updating tools/codify/rlm/requirements.in -> plugins/rlm-factory/...'
sed -i '' 's/tools\/codify\/rlm\/requirements\.in/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/codify/rlm/requirements.txt -> plugins/rlm-factory/...'
sed -i '' 's/tools\/codify\/rlm\/requirements\.txt/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/codify/rlm/rlm_config.py -> plugins/rlm-factory/skills/rlm-curator/scripts/rlm_config.py...'
sed -i '' 's/tools\/codify\/rlm\/rlm_config\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/rlm_config\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/codify\/rlm\/rlm_config\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/rlm_config\.py/g' "scripts/update_legacy_paths.py"
echo 'Updating tools/context-bundler/bundle.py -> plugins/context-bundler/scripts/bundle.py...'
sed -i '' 's/tools\/context-bundler\/bundle\.py/plugins\/context-bundler\/scripts\/bundle\.py/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/context-bundler/file-manifest.json -> plugins/context-bundler/file-manifest.json...'
sed -i '' 's/tools\/context-bundler\/file-manifest\.json/plugins\/context-bundler\/file-manifest\.json/g' "docs/tools/standalone/context-bundler/architecture.md"
sed -i '' 's/tools\/context-bundler\/file-manifest\.json/plugins\/context-bundler\/file-manifest\.json/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/curate/inventories/manage_tool_inventory.py -> plugins/tool-inventory/skills/tool-inventory/scripts/manage_tool_inventory.py...'
sed -i '' 's/tools\/curate\/inventories\/manage_tool_inventory\.py/plugins\/tool-inventory\/skills\/tool-inventory\/scripts\/manage_tool_inventory\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/curate\/inventories\/manage_tool_inventory\.py/plugins\/tool-inventory\/skills\/tool-inventory\/scripts\/manage_tool_inventory\.py/g' "scripts/update_legacy_paths.py"
echo 'Updating tools/curate/link-checker/check_broken_paths.py -> plugins/link-checker/skills/link-checker-agent/scripts/check_broken_paths.py...'
sed -i '' 's/tools\/curate\/link-checker\/check_broken_paths\.py/plugins\/link-checker\/skills\/link-checker-agent\/scripts\/check_broken_paths\.py/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/curate/link-checker/enrich_links_v2.py -> plugins/link-checker/skills/link-checker-agent/scripts/enrich_links_v2.py...'
sed -i '' 's/tools\/curate\/link-checker\/enrich_links_v2\.py/plugins\/link-checker\/skills\/link-checker-agent\/scripts\/enrich_links_v2\.py/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/curate/link-checker/find_source_links.py -> plugins/link-checker/skills/link-checker-agent/scripts/find_source_links.py...'
sed -i '' 's/tools\/curate\/link-checker\/find_source_links\.py/plugins\/link-checker\/skills\/link-checker-agent\/scripts\/find_source_links\.py/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/curate/link-checker/map_repository_files.py -> plugins/link-checker/skills/link-checker-agent/scripts/map_repository_files.py...'
sed -i '' 's/tools\/curate\/link-checker\/map_repository_files\.py/plugins\/link-checker\/skills\/link-checker-agent\/scripts\/map_repository_files\.py/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/curate/link-checker/smart_fix_links.py -> plugins/link-checker/skills/link-checker-agent/scripts/smart_fix_links.py...'
sed -i '' 's/tools\/curate\/link-checker\/smart_fix_links\.py/plugins\/link-checker\/skills\/link-checker-agent\/scripts\/smart_fix_links\.py/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/curate/rlm/cleanup_cache.py -> plugins/rlm-factory/skills/rlm-curator/scripts/cleanup_cache.py...'
sed -i '' 's/tools\/curate\/rlm\/cleanup_cache\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/cleanup_cache\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/curate\/rlm\/cleanup_cache\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/cleanup_cache\.py/g' "scripts/update_legacy_paths.py"
echo 'Updating tools/orchestrator/dual_loop/README.md -> plugins/agent-loops/personas/README.md...'
sed -i '' 's/tools\/orchestrator\/dual_loop\/README\.md/plugins\/agent-loops\/personas\/README\.md/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/orchestrator\/dual_loop\/README\.md/plugins\/agent-loops\/personas\/README\.md/g' "kitty-specs/002-dual-loop-spec-alignment/spec.md"
sed -i '' 's/tools\/orchestrator\/dual_loop\/README\.md/plugins\/agent-loops\/personas\/README\.md/g' "kitty-specs/002-dual-loop-spec-alignment/tasks.md"
echo 'Updating tools/orchestrator/verify_workflow_state.py -> plugins/spec-kitty-plugin/skills/spec-kitty-agent/scripts/verify_workflow_state.py...'
sed -i '' 's/tools\/orchestrator\/verify_workflow_state\.py/plugins\/spec-kitty-plugin\/skills\/spec-kitty-agent\/scripts\/verify_workflow_state\.py/g' "kitty-specs/004-verify-workflow-test/spec.md"
sed -i '' 's/tools\/orchestrator\/verify_workflow_state\.py/plugins\/spec-kitty-plugin\/skills\/spec-kitty-agent\/scripts\/verify_workflow_state\.py/g' "kitty-specs/004-verify-workflow-test/meta.json"
sed -i '' 's/tools\/orchestrator\/verify_workflow_state\.py/plugins\/spec-kitty-plugin\/skills\/spec-kitty-agent\/scripts\/verify_workflow_state\.py/g' "kitty-specs/006-dual-loop-kit/spec.md"
sed -i '' 's/tools\/orchestrator\/verify_workflow_state\.py/plugins\/spec-kitty-plugin\/skills\/spec-kitty-agent\/scripts\/verify_workflow_state\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/orchestrator\/verify_workflow_state\.py/plugins\/spec-kitty-plugin\/skills\/spec-kitty-agent\/scripts\/verify_workflow_state\.py/g' "kitty-specs/004-verify-workflow-test/plan.md"
sed -i '' 's/tools\/orchestrator\/verify_workflow_state\.py/plugins\/spec-kitty-plugin\/skills\/spec-kitty-agent\/scripts\/verify_workflow_state\.py/g' "kitty-specs/004-verify-workflow-test/tasks/WP-001.md"
sed -i '' 's/tools\/orchestrator\/verify_workflow_state\.py/plugins\/spec-kitty-plugin\/skills\/spec-kitty-agent\/scripts\/verify_workflow_state\.py/g' "archive-tests/unit/tools/orchestrator/test_verify_workflow_state.py"
echo 'Updating tools/retrieve/bundler/bundle.py -> plugins/context-bundler/scripts/bundle.py...'
sed -i '' 's/tools\/retrieve\/bundler\/bundle\.py/plugins\/context-bundler\/scripts\/bundle\.py/g' "docs/diagrams/workflows/curate-bundle.mmd"
sed -i '' 's/tools\/retrieve\/bundler\/bundle\.py/plugins\/context-bundler\/scripts\/bundle\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/retrieve\/bundler\/bundle\.py/plugins\/context-bundler\/scripts\/bundle\.py/g' "scripts/update_legacy_paths.py"
echo 'Updating tools/retrieve/rlm/inventory.py -> plugins/rlm-factory/skills/rlm-curator/scripts/inventory.py...'
sed -i '' 's/tools\/retrieve\/rlm\/inventory\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/inventory\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/retrieve\/rlm\/inventory\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/inventory\.py/g' "scripts/update_legacy_paths.py"
echo 'Updating tools/retrieve/rlm/query_cache.py -> plugins/rlm-factory/skills/rlm-curator/scripts/query_cache.py...'
sed -i '' 's/tools\/retrieve\/rlm\/query_cache\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/query_cache\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/retrieve\/rlm\/query_cache\.py/plugins\/rlm-factory\/skills\/rlm-curator\/scripts\/query_cache\.py/g' "scripts/update_legacy_paths.py"
echo 'Updating tools/rlm-factory/requirements.in -> plugins/rlm-factory/...'
sed -i '' 's/tools\/rlm-factory\/requirements\.in/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/README.md -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/README\.md/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/TOOL_INVENTORY.md -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/TOOL_INVENTORY\.md/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/base-manifests/tools/standalone/context-bundler/prompt.md -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/base-manifests\/tools\/standalone\/context-bundler\/prompt\.md/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/docs/diagrams/workflows/curate-bundle.mmd -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/docs\/diagrams\/workflows\/curate-bundle\.mmd/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/file-manifest.json -> plugins/context-bundler/file-manifest.json...'
sed -i '' 's/tools\/standalone\/context-bundler\/file-manifest\.json/plugins\/context-bundler\/file-manifest\.json/g' "specs/0006-rebuild-constitution/RED_TEAM_BUNDLE.md"
sed -i '' 's/tools\/standalone\/context-bundler\/file-manifest\.json/plugins\/context-bundler\/file-manifest\.json/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/context-bundler/prompt.md -> plugins/context-bundler/...'
sed -i '' 's/tools\/standalone\/context-bundler\/prompt\.md/plugins\/context-bundler\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/dual-loop-kit/README.md -> plugins/agent-loops/personas/README.md...'
sed -i '' 's/tools\/standalone\/dual-loop-kit\/README\.md/plugins\/agent-loops\/personas\/README\.md/g' "kitty-specs/006-dual-loop-kit/plan.md"
sed -i '' 's/tools\/standalone\/dual-loop-kit\/README\.md/plugins\/agent-loops\/personas\/README\.md/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/standalone\/dual-loop-kit\/README\.md/plugins\/agent-loops\/personas\/README\.md/g' "kitty-specs/006-dual-loop-kit/tasks.md"
sed -i '' 's/tools\/standalone\/dual-loop-kit\/README\.md/plugins\/agent-loops\/personas\/README\.md/g' "kitty-specs/006-dual-loop-kit/tasks/WP-001.md"
echo 'Updating tools/standalone/dual-loop-kit/prompt.md -> plugins/rlm-factory/skills/rlm-curator/references/prompt.md...'
sed -i '' 's/tools\/standalone\/dual-loop-kit\/prompt\.md/plugins\/rlm-factory\/skills\/rlm-curator\/references\/prompt\.md/g' "kitty-specs/006-dual-loop-kit/plan.md"
sed -i '' 's/tools\/standalone\/dual-loop-kit\/prompt\.md/plugins\/rlm-factory\/skills\/rlm-curator\/references\/prompt\.md/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/standalone\/dual-loop-kit\/prompt\.md/plugins\/rlm-factory\/skills\/rlm-curator\/references\/prompt\.md/g' "kitty-specs/006-dual-loop-kit/tasks.md"
sed -i '' 's/tools\/standalone\/dual-loop-kit\/prompt\.md/plugins\/rlm-factory\/skills\/rlm-curator\/references\/prompt\.md/g' "kitty-specs/006-dual-loop-kit/tasks/WP-001.md"
echo 'Updating tools/standalone/link-checker/README.md -> plugins/agent-loops/personas/README.md...'
sed -i '' 's/tools\/standalone\/link-checker\/README\.md/plugins\/agent-loops\/personas\/README\.md/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/link-checker/logic.mmd -> plugins/rlm-factory/skills/rlm-curator/references/logic.mmd...'
sed -i '' 's/tools\/standalone\/link-checker\/logic\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/logic\.mmd/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/link-checker/prompt.md -> plugins/rlm-factory/skills/rlm-curator/references/prompt.md...'
sed -i '' 's/tools\/standalone\/link-checker\/prompt\.md/plugins\/rlm-factory\/skills\/rlm-curator\/references\/prompt\.md/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/link-checker/unpacking.mmd -> plugins/rlm-factory/skills/rlm-curator/references/unpacking.mmd...'
sed -i '' 's/tools\/standalone\/link-checker\/unpacking\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/unpacking\.mmd/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/link-checker/workflow.mmd -> plugins/rlm-factory/skills/rlm-curator/references/workflow.mmd...'
sed -i '' 's/tools\/standalone\/link-checker\/workflow\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/workflow\.mmd/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/BLUEPRINT.md -> plugins/rlm-factory/skills/rlm-curator/references/BLUEPRINT.md...'
sed -i '' 's/tools\/standalone\/rlm-factory\/BLUEPRINT\.md/plugins\/rlm-factory\/skills\/rlm-curator\/references\/BLUEPRINT\.md/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/README.md -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/README\.md/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/distillation_process.mmd -> plugins/rlm-factory/skills/rlm-curator/references/distillation_process.mmd...'
sed -i '' 's/tools\/standalone\/rlm-factory\/distillation_process\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/distillation_process\.mmd/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/distiller_manifest.json -> plugins/rlm-factory/resources/distiller_manifest.json...'
sed -i '' 's/tools\/standalone\/rlm-factory\/distiller_manifest\.json/plugins\/rlm-factory\/resources\/distiller_manifest\.json/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/docs/diagrams/workflows/context-first-analysis-detailed.mmd -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/docs\/diagrams\/workflows\/context-first-analysis-detailed\.mmd/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/docs/diagrams/workflows/context-first-analysis.mmd -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/docs\/diagrams\/workflows\/context-first-analysis\.mmd/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/logic.mmd -> plugins/rlm-factory/skills/rlm-curator/references/logic.mmd...'
sed -i '' 's/tools\/standalone\/rlm-factory\/logic\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/logic\.mmd/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/manifest-index.json -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/manifest-index\.json/plugins\/rlm-factory\//g' "specs/0006-rebuild-constitution/RED_TEAM_BUNDLE.md"
sed -i '' 's/tools\/standalone\/rlm-factory\/manifest-index\.json/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/prompt.md -> plugins/rlm-factory/skills/rlm-curator/references/prompt.md...'
sed -i '' 's/tools\/standalone\/rlm-factory\/prompt\.md/plugins\/rlm-factory\/skills\/rlm-curator\/references\/prompt\.md/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/research/summary.md -> plugins/rlm-factory/skills/rlm-curator/references/research/summary.md...'
sed -i '' 's/tools\/standalone\/rlm-factory\/research\/summary\.md/plugins\/rlm-factory\/skills\/rlm-curator\/references\/research\/summary\.md/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/rlm_manifest.json -> plugins/rlm-factory/...'
sed -i '' 's/tools\/standalone\/rlm-factory\/rlm_manifest\.json/plugins\/rlm-factory\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/search_process.mmd -> plugins/rlm-factory/skills/rlm-curator/references/search_process.mmd...'
sed -i '' 's/tools\/standalone\/rlm-factory\/search_process\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/search_process\.mmd/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/unpacking.mmd -> plugins/rlm-factory/skills/rlm-curator/references/unpacking.mmd...'
sed -i '' 's/tools\/standalone\/rlm-factory\/unpacking\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/unpacking\.mmd/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/rlm-factory/workflow.mmd -> plugins/rlm-factory/skills/rlm-curator/references/workflow.mmd...'
sed -i '' 's/tools\/standalone\/rlm-factory\/workflow\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/workflow\.mmd/g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/vector-db/README.md -> plugins/vector-db/...'
sed -i '' 's/tools\/standalone\/vector-db\/README\.md/plugins\/vector-db\//g' "scripts/apply_tool_migration.sh"