#!/bin/bash
# Auto-generated tool migration script

echo 'Updating tools/business-rule-extraction/scripts/manifest_manager.py -> plugins/context-bundler/scripts/manifest_manager.py...'
sed -i '' 's/tools\/business-rule-extraction\/scripts\/manifest_manager\.py/plugins\/context-bundler\/scripts\/manifest_manager\.py/g' "broken_tool_references.md"
echo 'Updating tools/investigate/utils/next_number.py -> plugins/adr-manager/skills/adr-management/scripts/next_number.py...'
sed -i '' 's/tools\/investigate\/utils\/next_number\.py/plugins\/adr-manager\/skills\/adr-management\/scripts\/next_number\.py/g' "scripts/update_legacy_paths.py"
sed -i '' 's/tools\/investigate\/utils\/next_number\.py/plugins\/adr-manager\/skills\/adr-management\/scripts\/next_number\.py/g' "broken_tool_references.md"
echo 'Updating tools/investigate/utils/path_resolver.py -> plugins/context-bundler/scripts/path_resolver.py...'
sed -i '' 's/tools\/investigate\/utils\/path_resolver\.py/plugins\/context-bundler\/scripts\/path_resolver\.py/g' "broken_tool_references.md"
echo 'Updating tools/retrieve/bundler/manifest_manager.py -> plugins/context-bundler/scripts/manifest_manager.py...'
sed -i '' 's/tools\/retrieve\/bundler\/manifest_manager\.py/plugins\/context-bundler\/scripts\/manifest_manager\.py/g' "scripts/update_legacy_paths.py"
sed -i '' 's/tools\/retrieve\/bundler\/manifest_manager\.py/plugins\/context-bundler\/scripts\/manifest_manager\.py/g' "broken_tool_references.md"
echo 'Updating tools/standalone/xml-to-markdown/unpacking.mmd -> plugins/rlm-factory/skills/rlm-curator/references/unpacking.mmd...'
sed -i '' 's/tools\/standalone\/xml-to-markdown\/unpacking\.mmd/plugins\/rlm-factory\/skills\/rlm-curator\/references\/unpacking\.mmd/g' "broken_tool_references.md"
echo 'Updating tools/utils/path_resolver.py -> plugins/context-bundler/scripts/path_resolver.py...'
sed -i '' 's/tools\/utils\/path_resolver\.py/plugins\/context-bundler\/scripts\/path_resolver\.py/g' "broken_tool_references.md"
echo 'Updating tools/orchestrator/workflow_manager.py -> plugins/agent-loops/skills/orchestrator/scripts/agent_orchestrator.py...'
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "temp/constitution.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "specs/0001-mcp-to-cli-migration/operations_matrix.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "GEMINI.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "kitty-specs/005-safe-agent-zero/retrospective.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "tools/TOOL_INVENTORY.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "ADRs/036_workflow_shim_architecture.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "specs/0006-rebuild-constitution/RED_TEAM_BUNDLE.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "specs/0002-spec-0002/retrospective.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "specs/0001-mcp-to-cli-migration/spec.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "tasks/backlog/165_implement-pure-python-orchestration.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "scripts/update_legacy_paths.py"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "specs/0006-rebuild-constitution/retrospective.md"
sed -i '' 's/tools\/orchestrator\/workflow_manager\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "kitty-specs/006-dual-loop-kit/spec.md"
echo 'Updating tools/shared/bundler_core.py -> plugins/context-bundler/scripts/bundle.py...'
sed -i '' 's/tools\/shared\/bundler_core\.py/plugins\/context-bundler\/scripts\/bundle\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/shared\/bundler_core\.py/plugins\/context-bundler\/scripts\/bundle\.py/g' "ADRs/097_base_manifest_inheritance_architecture.md"
sed -i '' 's/tools\/shared\/bundler_core\.py/plugins\/context-bundler\/scripts\/bundle\.py/g' "docs/architecture/bundling/bundling-architecture-proposal.md"
sed -i '' 's/tools\/shared\/bundler_core\.py/plugins\/context-bundler\/scripts\/bundle\.py/g' "scripts/reconcile_tool_references.py"
sed -i '' 's/tools\/shared\/bundler_core\.py/plugins\/context-bundler\/scripts\/bundle\.py/g' "specs/0002-spec-0002/design-proposal-bundling-architecture.md"
echo 'Updating tools/bridge/ -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge\//plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/bridge\//plugins\/plugin-mapper\//g' "scripts/reconcile_tool_references.py"
echo 'Updating tools/bridge -> plugins/plugin-mapper/...'
sed -i '' 's/tools\/bridge/plugins\/plugin-mapper\//g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/bridge/plugins\/plugin-mapper\//g' "scripts/reconcile_tool_references.py"
echo 'Updating tools/orchestrator/dual_loop/ -> plugins/agent-loops/skills/orchestrator/scripts/agent_orchestrator.py...'
sed -i '' 's/tools\/orchestrator\/dual_loop\//plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/orchestrator\/dual_loop\//plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "kitty-specs/001-dual-loop-agent-architecture/retrospective.md"
sed -i '' 's/tools\/orchestrator\/dual_loop\//plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "kitty-specs/001-dual-loop-agent-architecture/tasks.md"
sed -i '' 's/tools\/orchestrator\/dual_loop\//plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "kitty-specs/006-dual-loop-kit/spec.md"
echo 'Updating tools/orchestrator/dual_loop/generate_strategy_packet.py -> plugins/agent-loops/skills/orchestrator/scripts/agent_orchestrator.py...'
sed -i '' 's/tools\/orchestrator\/dual_loop\/generate_strategy_packet\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/orchestrator\/dual_loop\/generate_strategy_packet\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "LEARNING/protocols/dual_loop_implementation_summary.md"
echo 'Updating tools/orchestrator/dual_loop/verify_inner_loop_result.py -> plugins/agent-loops/skills/orchestrator/scripts/agent_orchestrator.py...'
sed -i '' 's/tools\/orchestrator\/dual_loop\/verify_inner_loop_result\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/orchestrator\/dual_loop\/verify_inner_loop_result\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "LEARNING/protocols/dual_loop_implementation_summary.md"
echo 'Updating tools/orchestrator/test_verify_workflow_state.py -> plugins/agent-loops/skills/orchestrator/scripts/agent_orchestrator.py...'
sed -i '' 's/tools\/orchestrator\/test_verify_workflow_state\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "scripts/apply_tool_migration.sh"
sed -i '' 's/tools\/orchestrator\/test_verify_workflow_state\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "kitty-specs/004-verify-workflow-test/tasks.md"
sed -i '' 's/tools\/orchestrator\/test_verify_workflow_state\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "kitty-specs/004-verify-workflow-test/tasks/WP-001.md"
sed -i '' 's/tools\/orchestrator\/test_verify_workflow_state\.py/plugins\/agent-loops\/skills\/orchestrator\/scripts\/agent_orchestrator\.py/g' "kitty-specs/004-verify-workflow-test/plan.md"
echo 'Updating tools/curate/link-checker/ -> plugins/link-checker/...'
sed -i '' 's/tools\/curate\/link-checker\//plugins\/link-checker\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/curate/link-checker/fix_analysis_links.py -> plugins/link-checker/...'
sed -i '' 's/tools\/curate\/link-checker\/fix_analysis_links\.py/plugins\/link-checker\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/curate/link-checker/fix_pdf_links.py -> plugins/link-checker/...'
sed -i '' 's/tools\/curate\/link-checker\/fix_pdf_links\.py/plugins\/link-checker\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/link-checker/ -> plugins/link-checker/...'
sed -i '' 's/tools\/link-checker\//plugins\/link-checker\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/link-checker/INSTALL.md -> plugins/link-checker/...'
sed -i '' 's/tools\/standalone\/link-checker\/INSTALL\.md/plugins\/link-checker\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/link-checker/UNPACK_INSTRUCTIONS.md -> plugins/link-checker/...'
sed -i '' 's/tools\/standalone\/link-checker\/UNPACK_INSTRUCTIONS\.md/plugins\/link-checker\//g' "scripts/apply_tool_migration.sh"
echo 'Updating tools/standalone/link-checker/tool-bundle.md -> plugins/link-checker/...'
sed -i '' 's/tools\/standalone\/link-checker\/tool-bundle\.md/plugins\/link-checker\//g' "scripts/apply_tool_migration.sh"